-d /home/nooradintirhi/Documents/FPGA/RGB_LED/impl/gwsynthesis/RGB_LED.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst /home/nooradintirhi/Documents/FPGA/RGB_LED/src/RGB_LED.cst
-cfg /home/nooradintirhi/Documents/FPGA/RGB_LED/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
